fix-subscribe:fixing suscbribe with symbol
endenwer/tradingview-ws pull request #5
Opened 2022-09-28 15:15 UTC by reizhafajrian

i just add subscribe with symbol and remove unused code

2022-09-28 15:25 UTC, reizhafajrian commented
i think we can create dev branch for testing it,before merge to main branch

2022-10-03 16:07 UTC, endenwer commented
Thanks for pr, but I can't accept it as is. There is no tests, some strange files like `src/TradingViewWebsocket.ts`. And It is better to make different pr's for refactoring and new features.

2022-10-04 10:29 UTC, reizhafajrian commented
> Thanks for pr, but I can't accept it as is. There is no tests, some strange files like `src/TradingViewWebsocket.ts`. And It is better to make different pr's for refactoring and new features.

i think we can create new branch like dev branch

2023-11-27 20:33 UTC, CODLOP requested changes
how we can get ticks if callback is not disponible !!

2023-11-27 20:33 UTC, CODLOP commented on src/index.ts
> +        // callback(candles)
i don't know why you comment the callback !!

2023-11-27 20:33 UTC, CODLOP commented on src/index.ts
> +      if (event.params.p[1].sds_1?.s !== undefined) {
all event.params.p should be event.params

2023-11-27 20:33 UTC, CODLOP commented on src/index.ts
> +export async function connectAndSubscribe({ connection, symbols, timeframe = 1 }: GetCandlesParams) {
where callback param !!

2026-01-26 08:35 UTC, closed without merging